version: '3.8'

services:
  app:
    image: node:16
    build:
      context: .
    environment:
      DB_HOST: db  # Usando o nome correto do serviço
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: posts
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge
