version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app/backend:/usr/src/app/backend
      - ./app/frontend/public:/usr/src/app/frontend/public
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "30s", "node", "backend/server.js"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root   # Senha do usuário root
      MYSQL_DATABASE: posts       # Nome do banco de dados
      MYSQL_USER: app_user        # Usuário padrão (não root)
      MYSQL_PASSWORD: app_password # Senha do usuário padrão
    ports:
      - "3307:3306"
    volumes:
      # - db_data:/var/lib/mysql # Criar a pasta local
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
    # Volume para armazenar os dados do MySQL
